schema_version = "1.0.0"

id = "BLRigTool"
version = "0.1.0"
name = "BL Rig Tool"
tagline = "Rig tool for Blender. include Custom Display Shape, Generate Constraint(Exp), Rename Tool, Export to Unreal"
maintainer = "WRYC <wryc.artwork@gmail.com>"
type = "add-on"
tags = ["Animation", "Sequencer"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/WrycArtwork/BL-Rig-Tool"